#!/bin/vbash

set firewall ipv6 forward filter default-action 'accept'
set firewall ipv6 forward filter rule 5 action 'jump'
set firewall ipv6 forward filter rule 5 inbound-interface interface-name 'eth7'
set firewall ipv6 forward filter rule 5 jump-target 'WANv6_IN'

set firewall ipv6 input filter default-action 'accept'
set firewall ipv6 input filter rule 5 action 'jump'
set firewall ipv6 input filter rule 5 inbound-interface interface-name 'eth7'
set firewall ipv6 input filter rule 5 jump-target 'WANv6_LOCAL'

set firewall ipv6 name MGMT-IN default-action 'drop'
set firewall ipv6 name MGMT-IN rule 1 action 'accept'
set firewall ipv6 name MGMT-IN rule 1 description 'Allow Established/related'
set firewall ipv6 name MGMT-IN rule 1 state established 'enable'
set firewall ipv6 name MGMT-IN rule 1 state related 'enable'
set firewall ipv6 name MGMT-IN rule 18 action 'accept'
set firewall ipv6 name MGMT-IN rule 18 description 'Allow MGMT access from own range'
set firewall ipv6 name MGMT-IN rule 18 destination port '161,162,22,10222'
set firewall ipv6 name MGMT-IN rule 18 protocol 'tcp_udp'
set firewall ipv6 name MGMT-IN rule 18 source address '2001:67c:1104::/48'
set firewall ipv6 name MGMT-IN rule 20 action 'drop'
set firewall ipv6 name MGMT-IN rule 20 description 'Drop invalid'
set firewall ipv6 name MGMT-IN rule 20 state invalid 'enable'
set firewall ipv6 name MGMT-IN rule 21 action 'accept'
set firewall ipv6 name MGMT-IN rule 21 description 'ICMPv6'
set firewall ipv6 name MGMT-IN rule 21 protocol 'icmpv6'

set firewall ipv6 name WANv6_IN default-action 'drop'
set firewall ipv6 name WANv6_IN description 'WAN inbound traffic forwarded to LAN'
set firewall ipv6 name WANv6_IN rule 10 action 'accept'
set firewall ipv6 name WANv6_IN rule 10 description 'Allow established/related sessions'
set firewall ipv6 name WANv6_IN rule 10 state established 'enable'
set firewall ipv6 name WANv6_IN rule 10 state related 'enable'
set firewall ipv6 name WANv6_IN rule 20 action 'drop'
set firewall ipv6 name WANv6_IN rule 20 description 'Drop invalid state'
set firewall ipv6 name WANv6_IN rule 20 state invalid 'enable'
set firewall ipv6 name WANv6_IN rule 21 action 'accept'
set firewall ipv6 name WANv6_IN rule 21 description 'ICMPv6 allow'
set firewall ipv6 name WANv6_IN rule 21 protocol 'icmpv6'
set firewall ipv6 name WANv6_IN rule 31 action 'accept'
set firewall ipv6 name WANv6_IN rule 31 description 'Allow IPv6 Packet Too Big'
set firewall ipv6 name WANv6_IN rule 31 icmpv6 type-name 'packet-too-big'
set firewall ipv6 name WANv6_IN rule 31 protocol 'icmpv6'
set firewall ipv6 name WANv6_IN rule 40 action 'accept'
set firewall ipv6 name WANv6_IN rule 40 destination port '5201'
set firewall ipv6 name WANv6_IN rule 40 protocol 'tcp'
set firewall ipv6 name WANv6_IN rule 41 action 'accept'
set firewall ipv6 name WANv6_IN rule 41 destination port '80,443'
set firewall ipv6 name WANv6_IN rule 41 protocol 'tcp'
set firewall ipv6 name WANv6_IN rule 42 action 'accept'
set firewall ipv6 name WANv6_IN rule 42 destination port '22'
set firewall ipv6 name WANv6_IN rule 42 protocol 'tcp'
set firewall ipv6 name WANv6_IN rule 43 action 'accept'
set firewall ipv6 name WANv6_IN rule 43 destination port '4789'
set firewall ipv6 name WANv6_IN rule 43 protocol 'udp'
set firewall ipv6 name WANv6_IN rule 50 action 'accept'
set firewall ipv6 name WANv6_IN rule 50 destination address '2001:14ba:16e5:faa0::2'
set firewall ipv6 name WANv6_IN rule 50 protocol 'tcp'
set firewall ipv6 name WANv6_IN rule 50 source address '2001:67c:1104:ac::/64'

set firewall ipv6 name WANv6_LOCAL default-action 'drop'
set firewall ipv6 name WANv6_LOCAL description 'WAN inbound traffic to the router'
set firewall ipv6 name WANv6_LOCAL rule 10 action 'accept'
set firewall ipv6 name WANv6_LOCAL rule 10 description 'Allow established/related sessions'
set firewall ipv6 name WANv6_LOCAL rule 10 state established 'enable'
set firewall ipv6 name WANv6_LOCAL rule 10 state related 'enable'
set firewall ipv6 name WANv6_LOCAL rule 15 action 'accept'
set firewall ipv6 name WANv6_LOCAL rule 15 description 'Allow monitor access to SNMP'
set firewall ipv6 name WANv6_LOCAL rule 15 destination port '161'
set firewall ipv6 name WANv6_LOCAL rule 15 protocol 'tcp_udp'
set firewall ipv6 name WANv6_LOCAL rule 15 source address '2001:67c:1104::/48'
set firewall ipv6 name WANv6_LOCAL rule 20 action 'drop'
set firewall ipv6 name WANv6_LOCAL rule 20 description 'Drop invalid state'
set firewall ipv6 name WANv6_LOCAL rule 20 state invalid 'enable'
set firewall ipv6 name WANv6_LOCAL rule 21 action 'accept'
set firewall ipv6 name WANv6_LOCAL rule 21 destination port '80,443'
set firewall ipv6 name WANv6_LOCAL rule 21 protocol 'tcp'
set firewall ipv6 name WANv6_LOCAL rule 30 action 'accept'
set firewall ipv6 name WANv6_LOCAL rule 30 description 'Allow IPv6 icmp'
set firewall ipv6 name WANv6_LOCAL rule 30 protocol 'ipv6-icmp'
set firewall ipv6 name WANv6_LOCAL rule 31 action 'accept'
set firewall ipv6 name WANv6_LOCAL rule 31 description 'Allow IPv6 Packet Too Big'
set firewall ipv6 name WANv6_LOCAL rule 31 icmpv6 type-name 'packet-too-big'
set firewall ipv6 name WANv6_LOCAL rule 31 protocol 'icmpv6'
set firewall ipv6 name WANv6_LOCAL rule 40 action 'accept'
set firewall ipv6 name WANv6_LOCAL rule 40 description 'allow dhcpv6'
set firewall ipv6 name WANv6_LOCAL rule 40 destination port '546'
set firewall ipv6 name WANv6_LOCAL rule 40 protocol 'udp'
set firewall ipv6 name WANv6_LOCAL rule 40 source port '547'

