#!/bin/vbash

set interface eth7 in name 'wan-in'
set interface eth7 local name 'wan-local'

set ipv6-name MGMT-IN default-action 'drop'
set ipv6-name MGMT-IN rule 1 action 'accept'
set ipv6-name MGMT-IN rule 1 description 'Allow Established/related'
set ipv6-name MGMT-IN rule 1 state established 'enable'
set ipv6-name MGMT-IN rule 1 state related 'enable'
set ipv6-name MGMT-IN rule 18 action 'accept'
set ipv6-name MGMT-IN rule 18 description 'Allow MGMT access from own range'
set ipv6-name MGMT-IN rule 18 destination port '161,162,22,10222'
set ipv6-name MGMT-IN rule 18 protocol 'tcp_udp'
set ipv6-name MGMT-IN rule 18 source address '2001:67c:1104::/48'
set ipv6-name MGMT-IN rule 20 action 'drop'
set ipv6-name MGMT-IN rule 20 description 'Drop invalid'
set ipv6-name MGMT-IN rule 20 state invalid 'enable'
set ipv6-name MGMT-IN rule 21 action 'accept'
set ipv6-name MGMT-IN rule 21 description 'ICMPv6'
set ipv6-name MGMT-IN rule 21 protocol 'icmpv6'

set ipv6-name WANv6_IN default-action 'drop'
set ipv6-name WANv6_IN description 'WAN inbound traffic forwarded to LAN'
set ipv6-name WANv6_IN rule 10 action 'accept'
set ipv6-name WANv6_IN rule 10 description 'Allow established/related sessions'
set ipv6-name WANv6_IN rule 10 state established 'enable'
set ipv6-name WANv6_IN rule 10 state related 'enable'
set ipv6-name WANv6_IN rule 20 action 'drop'
set ipv6-name WANv6_IN rule 20 description 'Drop invalid state'
set ipv6-name WANv6_IN rule 20 state invalid 'enable'
set ipv6-name WANv6_IN rule 21 action 'accept'
set ipv6-name WANv6_IN rule 21 description 'ICMPv6 allow'
set ipv6-name WANv6_IN rule 21 protocol 'icmpv6'
set ipv6-name WANv6_IN rule 31 action 'accept'
set ipv6-name WANv6_IN rule 31 description 'Allow IPv6 Packet Too Big'
set ipv6-name WANv6_IN rule 31 icmpv6 type-name 'packet-too-big'
set ipv6-name WANv6_IN rule 31 protocol 'icmpv6'
set ipv6-name WANv6_IN rule 40 action 'accept'
set ipv6-name WANv6_IN rule 40 destination port '5201'
set ipv6-name WANv6_IN rule 40 protocol 'tcp'
set ipv6-name WANv6_IN rule 41 action 'accept'
set ipv6-name WANv6_IN rule 41 destination port '80,443'
set ipv6-name WANv6_IN rule 41 protocol 'tcp'
set ipv6-name WANv6_IN rule 42 action 'accept'
set ipv6-name WANv6_IN rule 42 destination port '22'
set ipv6-name WANv6_IN rule 42 protocol 'tcp'
set ipv6-name WANv6_IN rule 43 action 'accept'
set ipv6-name WANv6_IN rule 43 destination port '4789'
set ipv6-name WANv6_IN rule 43 protocol 'udp'
set ipv6-name WANv6_IN rule 50 action 'accept'
set ipv6-name WANv6_IN rule 50 destination address '2001:14ba:16e5:faa0::2'
set ipv6-name WANv6_IN rule 50 protocol 'tcp'
set ipv6-name WANv6_IN rule 50 source address '2001:67c:1104:ac::/64'

set ipv6-name WANv6_LOCAL default-action 'drop'
set ipv6-name WANv6_LOCAL description 'WAN inbound traffic to the router'
set ipv6-name WANv6_LOCAL rule 10 action 'accept'
set ipv6-name WANv6_LOCAL rule 10 description 'Allow established/related sessions'
set ipv6-name WANv6_LOCAL rule 10 state established 'enable'
set ipv6-name WANv6_LOCAL rule 10 state related 'enable'
set ipv6-name WANv6_LOCAL rule 15 action 'accept'
set ipv6-name WANv6_LOCAL rule 15 description 'Allow monitor access to SNMP'
set ipv6-name WANv6_LOCAL rule 15 destination port '161'
set ipv6-name WANv6_LOCAL rule 15 protocol 'tcp_udp'
set ipv6-name WANv6_LOCAL rule 15 source address '2001:67c:1104::/48'
set ipv6-name WANv6_LOCAL rule 20 action 'drop'
set ipv6-name WANv6_LOCAL rule 20 description 'Drop invalid state'
set ipv6-name WANv6_LOCAL rule 20 state invalid 'enable'
set ipv6-name WANv6_LOCAL rule 21 action 'accept'
set ipv6-name WANv6_LOCAL rule 21 destination port '80,443'
set ipv6-name WANv6_LOCAL rule 21 protocol 'tcp'
set ipv6-name WANv6_LOCAL rule 30 action 'accept'
set ipv6-name WANv6_LOCAL rule 30 description 'Allow IPv6 icmp'
set ipv6-name WANv6_LOCAL rule 30 protocol 'ipv6-icmp'
set ipv6-name WANv6_LOCAL rule 31 action 'accept'
set ipv6-name WANv6_LOCAL rule 31 description 'Allow IPv6 Packet Too Big'
set ipv6-name WANv6_LOCAL rule 31 icmpv6 type-name 'packet-too-big'
set ipv6-name WANv6_LOCAL rule 31 protocol 'icmpv6'
set ipv6-name WANv6_LOCAL rule 40 action 'accept'
set ipv6-name WANv6_LOCAL rule 40 description 'allow dhcpv6'
set ipv6-name WANv6_LOCAL rule 40 destination port '546'
set ipv6-name WANv6_LOCAL rule 40 protocol 'udp'
set ipv6-name WANv6_LOCAL rule 40 source port '547'

set ipv6-name WANv6_Tunnel_IN default-action 'drop'
set ipv6-name WANv6_Tunnel_IN rule 1 action 'accept'
set ipv6-name WANv6_Tunnel_IN rule 1 description 'Allow established/related sessions'
set ipv6-name WANv6_Tunnel_IN rule 1 state established 'enable'
set ipv6-name WANv6_Tunnel_IN rule 1 state related 'enable'
set ipv6-name WANv6_Tunnel_IN rule 2 action 'drop'
set ipv6-name WANv6_Tunnel_IN rule 2 description 'Drop invalid state'
set ipv6-name WANv6_Tunnel_IN rule 2 state invalid 'enable'
set ipv6-name WANv6_Tunnel_IN rule 40 action 'accept'
set ipv6-name WANv6_Tunnel_IN rule 40 description 'Allow established/related to k8s svc cidr'
set ipv6-name WANv6_Tunnel_IN rule 40 destination address '2001:67c:1104:fdb::/112'
set ipv6-name WANv6_Tunnel_IN rule 40 state established 'enable'
set ipv6-name WANv6_Tunnel_IN rule 40 state related 'enable'
set ipv6-name WANv6_Tunnel_IN rule 41 action 'drop'
set ipv6-name WANv6_Tunnel_IN rule 41 description 'Drop other traffic to k8s svc cidr from outside'
set ipv6-name WANv6_Tunnel_IN rule 41 destination address '2001:67c:1104:fdb::/112'

set ipv6-name WANv6_Tunnel_LOCAL default-action 'drop'
set ipv6-name WANv6_Tunnel_LOCAL rule 1 action 'accept'
set ipv6-name WANv6_Tunnel_LOCAL rule 1 description 'Allow established/related sessions'
set ipv6-name WANv6_Tunnel_LOCAL rule 1 state established 'enable'
set ipv6-name WANv6_Tunnel_LOCAL rule 1 state related 'enable'
set ipv6-name WANv6_Tunnel_LOCAL rule 2 action 'drop'
set ipv6-name WANv6_Tunnel_LOCAL rule 2 description 'Drop invalid state'
set ipv6-name WANv6_Tunnel_LOCAL rule 2 state invalid 'enable'
set ipv6-name WANv6_Tunnel_LOCAL rule 3 action 'accept'
set ipv6-name WANv6_Tunnel_LOCAL rule 3 description 'Allow IPv6 ICMP'
set ipv6-name WANv6_Tunnel_LOCAL rule 3 protocol 'ipv6-icmp'
set ipv6-name WANv6_Tunnel_LOCAL rule 4 action 'accept'
set ipv6-name WANv6_Tunnel_LOCAL rule 4 description 'Allow BGP from own networks'
set ipv6-name WANv6_Tunnel_LOCAL rule 4 destination port '179'
set ipv6-name WANv6_Tunnel_LOCAL rule 4 protocol 'tcp'
set ipv6-name WANv6_Tunnel_LOCAL rule 4 source address '2001:67c:1104::/48'
set ipv6-name WANv6_Tunnel_LOCAL rule 5 action 'accept'
set ipv6-name WANv6_Tunnel_LOCAL rule 5 destination group network-group 'link-local'

set name wan-in default-action 'drop'
set name wan-in enable-default-log
set name wan-in rule 1 action 'accept'
set name wan-in rule 1 description 'Allow established/related'
set name wan-in rule 1 state established 'enable'
set name wan-in rule 1 state related 'enable'
set name wan-in rule 2 action 'accept'
set name wan-in rule 2 description 'Internet -> LAN traffic'
set name wan-in rule 2 destination port '80,443'
set name wan-in rule 2 inbound-interface interface-name 'eth7'
set name wan-in rule 2 outbound-interface interface-name 'eth8.105'
set name wan-in rule 2 protocol 'tcp'

set name wan-local default-action 'drop'
set name wan-local enable-default-log
set name wan-local rule 1 action 'accept'
set name wan-local rule 1 description 'Allow ICMPv4'
set name wan-local rule 1 icmp type-name 'echo-request'
set name wan-local rule 1 limit burst '5'
set name wan-local rule 1 limit rate '2/second'
set name wan-local rule 1 protocol 'icmp'
set name wan-local rule 10 action 'accept'
set name wan-local rule 10 description 'Allow VPN'
set name wan-local rule 10 destination port '15820'
set name wan-local rule 10 protocol 'tcp_udp'
set name wan-local rule 20 action 'accept'
set name wan-local rule 20 description 'Allow GRE traffic'
set name wan-local rule 20 protocol 'gre'
set name wan-local rule 30 action 'accept'
set name wan-local rule 30 state established 'enable'
set name wan-local rule 30 state related 'enable'
set name wan-local rule 31 action 'accept'
set name wan-local rule 31 description 'Allow SSH to router from specific places'
set name wan-local rule 31 destination port '22'
set name wan-local rule 31 protocol 'tcp'
set name wan-local rule 31 source group address-group 'WORK-KAPSI'
set name wan-local rule 50 action 'accept'
set name wan-local rule 50 destination port '80,443'
set name wan-local rule 50 protocol 'tcp'

