#!/bin/vbash

set firewall ipv4 forward filter default-action 'accept'
set firewall ipv4 forward filter rule 5 action 'jump'
set firewall ipv4 forward filter rule 5 inbound-interface interface-name 'eth7'
set firewall ipv4 forward filter rule 5 jump-target 'wan-in'

set firewall ipv4 input filter default-action 'accept'
set firewall ipv4 input filter rule 5 action 'jump'
set firewall ipv4 input filter rule 5 inbound-interface interface-name 'eth7'
set firewall ipv4 input filter rule 5 jump-target 'wan-local'

set firewall ipv4 name wan-in default-action 'drop'
set firewall ipv4 name wan-in rule 1 action 'accept'
set firewall ipv4 name wan-in rule 1 description 'Allow established/related'
set firewall ipv4 name wan-in rule 1 state established 'enable'
set firewall ipv4 name wan-in rule 1 state related 'enable'
set firewall ipv4 name wan-in rule 10 action 'accept'
set firewall ipv4 name wan-in rule 10 connection-status nat 'destination'
set firewall ipv4 name wan-in rule 10 state new 'enable'

set firewall ipv4 name wan-local default-action 'drop'
set firewall ipv4 name wan-local rule 1 action 'accept'
set firewall ipv4 name wan-local rule 1 description 'Allow ICMPv4'
set firewall ipv4 name wan-local rule 1 icmp type-name 'echo-request'
set firewall ipv4 name wan-local rule 1 limit burst '5'
set firewall ipv4 name wan-local rule 1 limit rate '2/second'
set firewall ipv4 name wan-local rule 1 protocol 'icmp'
set firewall ipv4 name wan-local rule 10 action 'accept'
set firewall ipv4 name wan-local rule 10 description 'Allow VPN'
set firewall ipv4 name wan-local rule 10 destination port '15820'
set firewall ipv4 name wan-local rule 10 protocol 'tcp_udp'
set firewall ipv4 name wan-local rule 20 action 'accept'
set firewall ipv4 name wan-local rule 20 description 'Allow GRE traffic'
set firewall ipv4 name wan-local rule 20 protocol 'gre'
set firewall ipv4 name wan-local rule 30 action 'accept'
set firewall ipv4 name wan-local rule 30 state established 'enable'
set firewall ipv4 name wan-local rule 30 state related 'enable'
set firewall ipv4 name wan-local rule 31 action 'accept'
set firewall ipv4 name wan-local rule 31 description 'Allow SSH to router from specific places'
set firewall ipv4 name wan-local rule 31 destination port '22'
set firewall ipv4 name wan-local rule 31 protocol 'tcp'
set firewall ipv4 name wan-local rule 31 source group address-group 'WORK-KAPSI'
set firewall ipv4 name wan-local rule 50 action 'accept'
set firewall ipv4 name wan-local rule 50 destination port '80,443'
set firewall ipv4 name wan-local rule 50 protocol 'tcp'

